//! B.U.D.U — Blocklist & Unified Defence Utility.
//!
//! Entrypoint: load config, init logging, build the pipeline, then run the
//! proxy alongside a supervisor task (§9) that owns SIGHUP hot-reload,
//! periodic rate-limit GC, and graceful shutdown on SIGTERM/Ctrl-C — all
//! coordinated by a `CancellationToken`.

use std::path::PathBuf;
use std::sync::Arc;
use std::time::Duration;

use arc_swap::ArcSwap;
use budu_config::Config;
use budu_pipeline::{Pipeline, Reloadable};
use clap::{Parser, Subcommand};
use tokio_util::sync::CancellationToken;

mod ban;

#[derive(Parser)]
#[command(name = "budu", version, about = "B.U.D.U — inline reverse-proxy WAF")]
struct Cli {
    /// Path to the TOML config file.
    #[arg(short, long, default_value = "config/budu.toml", global = true)]
    config: PathBuf,

    #[command(subcommand)]
    command: Option<Command>,
}

#[derive(Subcommand)]
enum Command {
    /// Run the WAF proxy (default).
    Run,
    /// Load and validate the config, then exit.
    Check,
    /// Convert ModSecurity / OWASP CRS `SecRule` files into a B.U.D.U rules
    /// TOML (a migration aid — review the output before deploying).
    ImportCrs {
        /// Source `.conf` files in ModSecurity SecRule syntax.
        #[arg(required = true)]
        files: Vec<PathBuf>,
        /// Write the generated rules here (default: stdout).
        #[arg(short, long)]
        out: Option<PathBuf>,
    },
    /// Add an IP/CIDR to the blocklist file, optionally time-limited. The
    /// running proxy applies it on the next reload (SIGHUP / refresh timer).
    Ban {
        /// IP or CIDR to block, e.g. 203.0.113.45 or 203.0.113.0/24.
        target: String,
        /// Auto-expire after this long, e.g. 30m, 1h, 7d (omit = permanent).
        #[arg(long = "for", value_name = "DURATION")]
        duration: Option<String>,
        /// Signal the running proxy (SIGHUP) to apply immediately. Requires
        /// `[server] pidfile`.
        #[arg(long)]
        reload: bool,
    },
    /// Remove an IP/CIDR from the blocklist file.
    Unban {
        /// IP or CIDR to unblock.
        target: String,
        /// Signal the running proxy (SIGHUP) to apply immediately. Requires
        /// `[server] pidfile`.
        #[arg(long)]
        reload: bool,
    },
    /// List current blocklist-file entries with their remaining TTL.
    Bans,
}

fn main() -> anyhow::Result<()> {
    let cli = Cli::parse();

    match cli.command.unwrap_or(Command::Run) {
        Command::Check => {
            let cfg = budu_config::Config::load(&cli.config)?;
            // Also compile the pipeline so rules.toml / signatures.toml errors
            // surface here instead of at startup or on SIGHUP.
            let (pipeline, reloadable) = Pipeline::from_config(&cfg)?;
            let m = reloadable.metrics();
            println!(
                "config OK: listen={} upstream={} | stages={} rules={} signatures={} blocklist={} allowlist={}",
                cfg.server.listen,
                cfg.server.upstream,
                pipeline.len(),
                m.rules,
                m.signatures,
                m.blocklist,
                m.allowlist
            );
            Ok(())
        }
        Command::ImportCrs { files, out } => import_crs(files, out),
        Command::Ban { target, duration, reload } => {
            ban::ban(&Config::load(&cli.config)?, &target, duration.as_deref(), reload)
        }
        Command::Unban { target, reload } => {
            ban::unban(&Config::load(&cli.config)?, &target, reload)
        }
        Command::Bans => ban::list(&Config::load(&cli.config)?),
        Command::Run => run(cli.config),
    }
}

/// Convert ModSecurity/CRS `.conf` files into a B.U.D.U rules TOML, writing to a
/// file or stdout, and print a conversion report (counts + skips) to stderr.
fn import_crs(files: Vec<PathBuf>, out: Option<PathBuf>) -> anyhow::Result<()> {
    let mut input = String::new();
    for f in &files {
        let text = std::fs::read_to_string(f)
            .map_err(|e| anyhow::anyhow!("reading {}: {e}", f.display()))?;
        input.push_str(&text);
        input.push('\n');
    }

    let report = budu_rules::modsec::convert(&input);
    let header = format!(
        "# Generated by `budu import-crs` from {} file(s).\n\
         # Converted {} source rule(s); skipped {}. REVIEW before deploying,\n\
         # then validate with `budu --config <cfg> check`.\n\n",
        files.len(),
        report.converted,
        report.skipped.len()
    );

    match &out {
        Some(path) => {
            std::fs::write(path, format!("{header}{}", report.toml))
                .map_err(|e| anyhow::anyhow!("writing {}: {e}", path.display()))?;
            eprintln!("wrote {} ({} rule blocks)", path.display(), report.converted);
        }
        None => print!("{header}{}", report.toml),
    }

    eprintln!("--- import-crs report ---");
    eprintln!("converted: {}", report.converted);
    eprintln!("skipped:   {}", report.skipped.len());
    for s in &report.skipped {
        eprintln!("  skip [{}]: {}", s.id, s.reason);
    }
    if !report.warnings.is_empty() {
        let unique: std::collections::BTreeSet<&String> = report.warnings.iter().collect();
        eprintln!("warnings:");
        for w in unique {
            eprintln!("  {w}");
        }
    }
    Ok(())
}

fn run(config_path: PathBuf) -> anyhow::Result<()> {
    let initial = Config::load(&config_path)?;
    init_tracing(&initial)?;
    let (pipeline, reloadable) = Pipeline::from_config(&initial)?;
    let metrics = Arc::new(budu_common::Metrics::default());
    let admin_listen = initial.metrics.listen;
    // Write the pidfile (if configured) so `budu ban --reload` can find us; the
    // guard removes it on the way out.
    let _pidfile = ban::PidFile::write(&initial.server.pidfile)?;
    let config = Arc::new(ArcSwap::from_pointee(initial));
    let pipeline = Arc::new(pipeline);

    let rt = tokio::runtime::Builder::new_multi_thread()
        .enable_all()
        .build()?;

    rt.block_on(async move {
        let cancel = CancellationToken::new();

        // Supervisor: SIGHUP reload + maintenance + shutdown signalling (§9).
        let supervisor = tokio::spawn(supervise(
            config.clone(),
            config_path,
            reloadable.clone(),
            cancel.clone(),
        ));

        // Admin endpoint (/metrics, /healthz), only if configured.
        let admin = admin_listen.map(|addr| {
            tokio::spawn(budu_proxy::serve_admin(
                addr,
                metrics.clone(),
                reloadable.clone(),
                cancel.clone(),
            ))
        });

        let result = budu_proxy::run(config, pipeline, metrics, cancel.clone()).await;

        // Server returned (cancelled or errored) → stop the rest too.
        cancel.cancel();
        let _ = supervisor.await;
        if let Some(admin) = admin {
            let _ = admin.await;
        }
        result
    })
}

/// Long-lived supervisor task (Tokio + `CancellationToken` + `select!`, §9).
/// Owns config hot-reload on SIGHUP, periodic rate-limit GC, and converts a
/// shutdown signal into cancellation for the whole process.
async fn supervise(
    config: Arc<ArcSwap<Config>>,
    config_path: PathBuf,
    reloadable: Reloadable,
    cancel: CancellationToken,
) {
    let mut maintenance = tokio::time::interval(Duration::from_secs(60));
    maintenance.set_missed_tick_behavior(tokio::time::MissedTickBehavior::Skip);

    let mut sighup = hangup_stream();

    // Pull external blocklist feeds once at startup (merges with inline+file).
    if let Err(e) = reloadable.refresh_blocklist(&config.load_full()).await {
        tracing::error!(error = %e, "initial blocklist refresh failed");
    }

    // Periodic blocklist refresh, if configured (refresh_secs = 0 → startup only).
    let refresh_secs = config.load().reputation.refresh_secs;
    let mut blocklist_refresh = (refresh_secs > 0).then(|| {
        let mut i = tokio::time::interval(Duration::from_secs(refresh_secs));
        i.set_missed_tick_behavior(tokio::time::MissedTickBehavior::Skip);
        i.reset(); // skip the immediate first tick (we just fetched above)
        i
    });

    loop {
        tokio::select! {
            _ = cancel.cancelled() => break,

            _ = shutdown_signal() => {
                tracing::info!("shutdown signal received; cancelling");
                cancel.cancel();
                break;
            }

            _ = sighup.recv() => {
                tracing::info!("SIGHUP: reloading config + rules");
                match Config::load(&config_path) {
                    Ok(cfg) => {
                        if let Err(e) = reloadable.apply(&cfg) {
                            tracing::error!(error = %e, "signature reload failed; keeping current rules");
                        }
                        if let Err(e) = reloadable.refresh_blocklist(&cfg).await {
                            tracing::error!(error = %e, "blocklist reload failed; keeping current");
                        }
                        config.store(Arc::new(cfg));
                        let m = reloadable.metrics();
                        tracing::info!(
                            signatures = m.signatures,
                            blocklist = m.blocklist,
                            "reload complete"
                        );
                    }
                    Err(e) => tracing::error!(error = %e, "reload failed to read config; keeping current"),
                }
            }

            _ = tick(&mut blocklist_refresh) => {
                let cfg = config.load_full();
                match reloadable.refresh_blocklist(&cfg).await {
                    Ok(()) => tracing::info!(blocklist = reloadable.metrics().blocklist, "blocklist refreshed"),
                    Err(e) => tracing::error!(error = %e, "blocklist refresh failed; keeping current"),
                }
            }

            _ = maintenance.tick() => {
                reloadable.run_maintenance();
                let m = reloadable.metrics();
                tracing::debug!(rate_buckets = m.rate_buckets, "maintenance tick");
            }
        }
    }
    tracing::debug!("supervisor stopped");
}

/// Await the next tick of an optional interval; never resolves when `None`, so
/// it sits harmlessly in `select!` when periodic refresh is disabled.
async fn tick(timer: &mut Option<tokio::time::Interval>) {
    match timer {
        Some(t) => {
            t.tick().await;
        }
        None => std::future::pending().await,
    }
}

/// A SIGHUP receiver on unix; a never-firing stand-in elsewhere.
#[cfg(unix)]
fn hangup_stream() -> tokio::signal::unix::Signal {
    tokio::signal::unix::signal(tokio::signal::unix::SignalKind::hangup())
        .expect("install SIGHUP handler")
}

/// Resolve on Ctrl-C or SIGTERM (systemd stop).
async fn shutdown_signal() {
    let ctrl_c = async {
        let _ = tokio::signal::ctrl_c().await;
    };

    #[cfg(unix)]
    let terminate = async {
        if let Ok(mut sig) =
            tokio::signal::unix::signal(tokio::signal::unix::SignalKind::terminate())
        {
            sig.recv().await;
        }
    };
    #[cfg(not(unix))]
    let terminate = std::future::pending::<()>();

    tokio::select! {
        _ = ctrl_c => {}
        _ = terminate => {}
    }
}

/// Init logging. App logs go to stdout (JSON); when `log.audit_file` is set,
/// events on the `audit` target are split off to that file instead (§12 step 5),
/// keeping the audit trail clean and separate from operational logs.
fn init_tracing(cfg: &Config) -> anyhow::Result<()> {
    use tracing_subscriber::{filter::filter_fn, fmt, prelude::*, EnvFilter};

    let env = || {
        EnvFilter::try_from_env("BUDU_LOG")
            .or_else(|_| EnvFilter::try_new("info"))
            .unwrap_or_default()
    };

    let audit_path = cfg.log.audit_file.trim();
    if audit_path.is_empty() {
        // No dedicated audit sink: everything (audit included) goes to stdout.
        tracing_subscriber::registry()
            .with(fmt::layer().json().with_filter(env()))
            .init();
        return Ok(());
    }

    let file = std::fs::OpenOptions::new()
        .create(true)
        .append(true)
        .open(audit_path)
        .map_err(|e| anyhow::anyhow!("opening audit_file {audit_path}: {e}"))?;
    let audit_writer = AuditFile(Arc::new(std::sync::Mutex::new(file)));

    // stdout: app logs at the env level, minus the audit target.
    let stdout_layer = fmt::layer()
        .json()
        .with_filter(env())
        .with_filter(filter_fn(|m| m.target() != "audit"));
    // file: only the audit target, always.
    let audit_layer = fmt::layer()
        .json()
        .with_writer(audit_writer)
        .with_filter(filter_fn(|m| m.target() == "audit"));

    tracing_subscriber::registry()
        .with(stdout_layer)
        .with(audit_layer)
        .init();
    Ok(())
}

/// A `MakeWriter` that appends to a shared audit file under a mutex.
#[derive(Clone)]
struct AuditFile(Arc<std::sync::Mutex<std::fs::File>>);

impl<'a> tracing_subscriber::fmt::MakeWriter<'a> for AuditFile {
    type Writer = AuditGuard<'a>;
    fn make_writer(&'a self) -> Self::Writer {
        AuditGuard(self.0.lock().unwrap_or_else(|e| e.into_inner()))
    }
}

struct AuditGuard<'a>(std::sync::MutexGuard<'a, std::fs::File>);

impl std::io::Write for AuditGuard<'_> {
    fn write(&mut self, buf: &[u8]) -> std::io::Result<usize> {
        self.0.write(buf)
    }
    fn flush(&mut self) -> std::io::Result<()> {
        self.0.flush()
    }
}
